[[main]]
name = "Sobre"
url = "/#about"
weight = 2

[[main]]
name = "Habilidades"
url = "/#skills"
weight = 3

[[main]]
name = "Experiência"
url = "/#experience"
weight = 4

[[main]]
name = "Contato"
url = "/#contact"
weight = 5

[[main]]
name = "Tech Stack"
url = "/#technical"
weight = 4.5

[[main]]
name = "Blog"
url = "/pt/blog/"
weight = 60

[[main]]
name = "Contribuições"
url = "/pt/contributions/"
weight = 51
pre = "contributions"
